[package]
name = "codchi-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
codchi-api.workspace = true
codchi-shared.workspace = true
async-trait.workspace = true
axum.workspace = true
tokio.workspace = true
bytes.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true

[dev-dependencies]
tower.workspace = true
http-body-util.workspace = true

[lib]
name = "codchi_server"
path = "src/lib.rs"

[[bin]]
name = "codchi-server"
path = "src/main.rs"
