[workspace]
resolver = "2"
members = [
    "codchi-api",
    "codchi-server",
    "codchi-cli",
    "codchi-shared",
    "codchi-container-utils",
]
exclude = [
    "beta/*",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
codchi-api = { path = "./codchi-api" }
codchi-shared = { path = "./codchi-shared" }
codchi-server = { path = "./codchi-server" }
async-trait = "0.1"
axum = "0.8"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "signal", "time", "process"] }
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
bytes = "1"
serde_urlencoded = "0.7"
tower = { version = "0.5", features = ["util"] }
chrono = { version = "0.4", default-features = false, features = ["serde", "clock", "std"] }
uuid = { version = "1", features = ["v7", "serde"] }
schemars = { version = "0.8", features = ["chrono", "uuid1", "derive"] }
aide = { version = "0.14", default-features = false }
futures-core = "0.3"
indexmap = "2"
percent-encoding = "2"
serde = "1"
serde_json = "1"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
proptest = "1"
tempfile = "3"

[profile.release]
lto = true
strip = true
