[workspace]
resolver = "2"
members = [
    "codchi-api",
    "codchi-server",
    "codchi-cli",
    "codchi-shared",
    "codchi-container-utils",
]
exclude = [
    "beta/*",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
codchi-api = { path = "./codchi-api" }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock", "std"] }
uuid = { version = "1", features = ["v7", "serde"] }
schemars = { version = "0.8", features = ["chrono", "uuid1", "derive"] }
aide = { version = "0.14", default-features = false }
futures-core = "0.3"
indexmap = "2"
percent-encoding = "2"
serde = "1"
serde_json = "1"
thiserror = "2.0"
futures = "0.3"
proptest = "1"

[profile.release]
lto = true
strip = true
