[package]
name = "shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
nightly = []

[dependencies]
anyhow.workspace = true
rand.workspace = true
log.workspace = true
